import type { Metadata } from "next";
import "../../globals.css";
import Header from "./_landingComponents/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-gradient-to-b from-[#101212] to-[#08201D] min-h-screen flex flex-col">
      <Header />
      <main className="pt-16 lg:pt-20 flex-1">
        {children}
      </main>
    </div>
  );
}
