import type { Metadata } from "next";
import LandingPageHeader from "./_landingComponent/header/Header";
// import "globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <main className="">
        <LandingPageHeader />
        {children}
      </main>
    </div>
  );
}
